server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: ${digit-kingdom.datasource.driver-class-name}
      url: jdbc:mysql://${digit-kingdom.datasource.host}:${digit-kingdom.datasource.port}/${digit-kingdom.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${digit-kingdom.datasource.username}
      password: ${digit-kingdom.datasource.password}
  profiles:
    active: dev
  security:
    user:
      name: user
      password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6378
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8

logging:
  level:
    com:
      group:
        digitkingdom:
          mapper: debug
          service: info
          controller: info

mybatis:
  type-aliases-package: "com.async.digitkingdom"
  mapper-locations: "classpath:mapper/*xml"
  configuration:
    map-underscore-to-camel-case: true

digit-kingdom:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: digit-kingdom
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

pagehelper:
  # 设置方言，此处指定 MySQL 数据库
  helper-dialect: mysql
  # 是否启动合理化，默认是 false。
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages（最大页数）会查询最后一页。
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 是否支持接口参数来传递分页参数，默认false
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql
  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  page-size-zero: true